erDiagram
    direction LR
    EDICION ||--|{ CATEGORIA : agrupa
    EDICION ||--o{ BANNER_INICIO : muestra
    CATEGORIA ||--o{ VOTACION : contiene
    VOTACION ||--|{ OPCION : ofrece
    VOTACION ||--o{ VOTO : registra
    OPCION ||--o{ VOTO : recibe
    USUARIO ||--o{ VOTO : emite
    USUARIO |o--o{ REGISTRO_AUDITORIA : genera
    EDICION {
        bigint id PK
        smallint anio UK
        varchar estado
        smallint votos_por_usuario
        bool votaciones_pausadas
        bigint creado_por FK "soporte"
        bigint actualizado_por FK "soporte"
    }
    CATEGORIA {
        bigint id PK
        bigint edicion_id FK
        varchar nombre
        varchar slug
        bigint creado_por FK "soporte"
        bigint actualizado_por FK "soporte"
    }
    VOTACION {
        bigint id PK
        bigint categoria_id FK
        varchar titulo
        datetime fecha_apertura
        datetime fecha_cierre
        bigint creado_por FK "soporte"
        bigint actualizado_por FK "soporte"
    }
    OPCION {
        bigint id PK
        bigint votacion_id FK
        varchar nombre
        bool activa
        bigint creado_por FK "soporte"
        bigint actualizado_por FK "soporte"
    }
    USUARIO {
        bigint id PK
        varchar email UK
        varchar numero_documento UK
        bool correo_verificado
        varchar rol
    }
    VOTO {
        bigint id PK
        bigint usuario_id FK
        bigint votacion_id FK
        bigint opcion_id FK
        varchar codigo_comprobante UK
    }
    REGISTRO_AUDITORIA {
        bigint id PK
        bigint usuario_id FK
        varchar accion
        datetime fecha_hora
    }
    BANNER_INICIO {
        bigint id PK
        bigint edicion_id FK
        varchar imagen
        bigint creado_por FK "soporte"
        bigint actualizado_por FK "soporte"
    }
