# Generated by Django 5.2.17 on 2026-10-02 22:43

import django.db.models.deletion
import django.utils.timezone
import votaciones.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('votante', 'Votante'), ('administrador', 'Administrador')], default='votante', max_length=20)),
                ('acepta_tratamiento_datos', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'usuario',
            },
            managers=[
                ('objects', votaciones.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='Edicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('anio', models.PositiveSmallIntegerField(unique=True, verbose_name='año')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cerrada', 'Cerrada')], default='activa', max_length=10)),
            ],
            options={
                'verbose_name': 'edición',
                'verbose_name_plural': 'ediciones',
                'db_table': 'edicion',
                'ordering': ['-anio'],
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_fin__gte', models.F('fecha_inicio'))), name='edicion_fechas_validas')],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(blank=True, max_length=60)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('edicion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='votaciones.edicion')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'db_table': 'categoria',
                'ordering': ['edicion', 'orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=40)),
                ('entidad', models.CharField(max_length=40)),
                ('entidad_id', models.CharField(blank=True, max_length=40)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de auditoría',
                'verbose_name_plural': 'registros de auditoría',
                'db_table': 'registro_auditoria',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Votacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.URLField(blank=True)),
                ('fecha_apertura', models.DateTimeField()),
                ('fecha_cierre', models.DateTimeField()),
                ('votos_por_usuario', models.PositiveSmallIntegerField(default=1)),
                ('visibilidad_resultados', models.CharField(choices=[('tiempo_real', 'En tiempo real'), ('al_cierre', 'Al cierre'), ('no_publicar', 'No publicar')], default='al_cierre', max_length=15)),
                ('publicada', models.BooleanField(default=False)),
                ('cerrada_manualmente', models.BooleanField(default=False)),
                ('resultados_publicados', models.BooleanField(default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votaciones', to='votaciones.categoria')),
            ],
            options={
                'verbose_name': 'votación',
                'verbose_name_plural': 'votaciones',
                'db_table': 'votacion',
                'ordering': ['fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.URLField(blank=True)),
                ('enlace_multimedia', models.URLField(blank=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('votacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opciones', to='votaciones.votacion')),
            ],
            options={
                'verbose_name': 'opción',
                'verbose_name_plural': 'opciones',
                'db_table': 'opcion',
                'ordering': ['votacion', 'orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('codigo_comprobante', models.CharField(max_length=20, unique=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votos', to='votaciones.opcion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votos', to=settings.AUTH_USER_MODEL)),
                ('votacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votos', to='votaciones.votacion')),
            ],
            options={
                'verbose_name': 'voto',
                'verbose_name_plural': 'votos',
                'db_table': 'voto',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('edicion', 'nombre'), name='categoria_nombre_unico_por_edicion'),
        ),
        migrations.AddConstraint(
            model_name='votacion',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_cierre__gt', models.F('fecha_apertura'))), name='votacion_cierre_posterior_apertura'),
        ),
        migrations.AddConstraint(
            model_name='votacion',
            constraint=models.CheckConstraint(condition=models.Q(('votos_por_usuario__gte', 1)), name='votacion_minimo_un_voto'),
        ),
        migrations.AddIndex(
            model_name='voto',
            index=models.Index(fields=['usuario', 'votacion'], name='voto_usuario_votacion_idx'),
        ),
    ]
