# Generated by Django 5.2.17 on 2026-10-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='pedir_documento',
            field=models.BooleanField(default=False, help_text='Pedir tipo y número de documento al registrarse (cada documento, una sola cuenta).'),
        ),
    ]
