# Generated by Django 5.2.17 on 2026-10-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0002_slugs_urls_amigables'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerInicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('subtitulo', models.CharField(blank=True, max_length=250)),
                ('imagen', models.ImageField(upload_to='banners/')),
                ('texto_alternativo', models.CharField(help_text='Descripción de la imagen para lectores de pantalla.', max_length=200)),
                ('texto_boton', models.CharField(blank=True, max_length=40)),
                ('enlace_boton', models.CharField(blank=True, help_text='Ruta del sitio (/2027) o URL http(s).', max_length=300)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'banner de inicio',
                'verbose_name_plural': 'banners de inicio',
                'db_table': 'banner_inicio',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_organizacion', models.CharField(default='Fundación Festival de la Leyenda Vallenata', max_length=150)),
                ('telefono', models.CharField(default='(+57) 315-746 3143', max_length=40)),
                ('direccion', models.CharField(default='Carrera 19 No. 6N-39, Valledupar, Colombia', max_length=200)),
                ('correo', models.EmailField(default='presidencia@festivalvallenato.com', max_length=254)),
                ('texto_pie', models.TextField(blank=True, default='Diseño académico original: no representa la marca oficial del Festival ni de la Fundación.')),
            ],
            options={
                'verbose_name': 'configuración del sitio',
                'verbose_name_plural': 'configuración del sitio',
                'db_table': 'configuracion_sitio',
            },
        ),
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('url', models.URLField()),
                ('icono', models.CharField(choices=[('facebook', 'Facebook'), ('twitter-x', 'X'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp'), ('spotify', 'Spotify'), ('globe', 'Sitio web')], default='globe', max_length=20)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'red social',
                'verbose_name_plural': 'redes sociales',
                'db_table': 'red_social',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
