# Generated by Django 5.2.17 on 2026-10-03 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0003_sitio_banners_redes'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='icono_imagen',
            field=models.ImageField(blank=True, help_text='Ícono propio subido desde el equipo; reemplaza al ícono de la lista.', upload_to='iconos/'),
        ),
        migrations.AddField(
            model_name='edicion',
            name='presentacion_categorias',
            field=models.CharField(choices=[('tarjetas', 'Tarjetas'), ('lista', 'Lista'), ('mosaico', 'Mosaico'), ('compacta', 'Compacta'), ('destacada', 'Destacada')], default='tarjetas', help_text='Cómo se muestran las categorías de la edición al público.', max_length=15),
        ),
        migrations.AddField(
            model_name='opcion',
            name='audio',
            field=models.FileField(blank=True, help_text='Archivo de audio subido (MP3, OGG, WAV, M4A o WebM).', upload_to='audios/'),
        ),
        migrations.AddField(
            model_name='opcion',
            name='texto_audio',
            field=models.TextField(blank=True, help_text='Letra o transcripción del audio, para accesibilidad.'),
        ),
        migrations.AddField(
            model_name='votacion',
            name='icono_imagen',
            field=models.ImageField(blank=True, help_text='Ícono propio subido desde el equipo; reemplaza al ícono de la lista.', upload_to='iconos/'),
        ),
        migrations.AddField(
            model_name='votacion',
            name='presentacion_opciones',
            field=models.CharField(choices=[('tarjetas', 'Tarjetas'), ('lista', 'Lista'), ('mosaico', 'Mosaico'), ('compacta', 'Compacta'), ('reproductor', 'Reproductor')], default='tarjetas', help_text='Cómo se muestran las opciones de la votación al público.', max_length=15),
        ),
    ]
