# Generated by Django 5.2.17 on 2026-10-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0005_banner_edicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='modo_banner',
            field=models.CharField(choices=[('fijo', 'Banner fijo'), ('carrusel', 'Carrusel')], default='carrusel', max_length=10),
        ),
        migrations.AlterField(
            model_name='bannerinicio',
            name='titulo',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
