# Generated by Django 5.2.17 on 2026-10-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0006_banner_modo_y_titulo_opcional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(help_text='Revista en PDF (máximo 50 MB).', upload_to='revistas/')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('publicada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'revista',
                'verbose_name_plural': 'revistas',
                'db_table': 'revista',
                'ordering': ['orden', '-publicada_en'],
            },
        ),
    ]
