# Generated by Django 5.2.17 on 2026-10-03 15:46

from django.db import migrations, models


def verificar_cuentas_existentes(apps, schema_editor):
    """Las cuentas creadas antes de exigir la confirmación del correo siguen pudiendo votar."""
    apps.get_model("votaciones", "Usuario").objects.update(correo_verificado=True)


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('votaciones', '0012_configuracion_votacion_edicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='correo_verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('TI', 'Tarjeta de identidad'), ('PA', 'Pasaporte'), ('PPT', 'Permiso por protección temporal')], max_length=3),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(fields=('tipo_documento', 'numero_documento'), name='usuario_documento_unico'),
        ),
        migrations.RunPython(verificar_cuentas_existentes, migrations.RunPython.noop),
    ]
